###Primer ejemplo
curl -X 'GET' \
  'http://127.0.0.1:8000/' \
  -H 'accept: application/json'

###Segundo ejemplo
curl -X 'GET' \
  'http://127.0.0.1:8000/ping' \
  -H 'accept: application/json'